// frontend-vue/src/App.vue
<template>
  <div class="app-container">
    <header class="app-header">
      <h1 class="app-title">Amazon収益レポート管理</h1>
      <nav class="app-nav">
        <ul class="nav-list">
          <li class="nav-item">
            <router-link to="/" class="nav-link" active-class="active"
              >レポートアップロード</router-link
            >
          </li>
          <li class="nav-item">
            <router-link
              to="/monthly-summary"
              class="nav-link"
              active-class="active"
              >月別サマリー</router-link
            >
          </li>
          <li class="nav-item">
            <router-link to="/sku-names" class="nav-link" active-class="active"
              >SKU名管理</router-link
            >
          </li>
          <li class="nav-item">
            <router-link
              to="/parent-sku-names"
              class="nav-link"
              active-class="active"
              >親SKU登録</router-link
            >
          </li>
          <li class="nav-item">
            <router-link to="/purchase" class="nav-link" active-class="active"
              >仕入れ登録</router-link
            >
          </li>
          <li class="nav-item">
            <router-link
              to="/transaction-data"
              class="nav-link"
              active-class="active"
              >トランザクションデータ一覧</router-link
            >
          </li>
        </ul>
      </nav>
    </header>
    <main class="app-main">
      <router-view></router-view>
    </main>
  </div>
</template>

<script setup lang="ts">
// App logic here if needed
</script>

<style>
/* Copy styles from App.css and index.css later */
</style>

// frontend/src/App.tsx
import { Routes, Route, NavLink } from 'react-router-dom';
import UploadPage from './pages/UploadPage';
import SkuNamePage from './pages/SkuNamePage'; // SkuNamePageをインポート
import ParentSkuPage from './pages/ParentSkuPage'; // ParentSkuPageをインポート
import MonthlySummaryPage from './pages/MonthlySummaryPage';
import PurchasePage from './pages/PurchasePage'; // PurchasePageをインポート
import './App.css';

function App() {
  return (
    <div className="app-container">
      <header className="app-header">
        <h1 className="app-title">Amazon収益レポート管理</h1>
        <nav className="app-nav">
          <ul className="nav-list">
            <li className="nav-item">
              <NavLink to="/" className={({ isActive }) => "nav-link" + (isActive ? " active" : "")}>レポートアップロード</NavLink>
            </li>
           <li className="nav-item">
             <NavLink to="/monthly-summary" className={({ isActive }) => "nav-link" + (isActive ? " active" : "")}>月別サマリー</NavLink>
           </li>
           <li className="nav-item">
              <NavLink to="/sku-names" className={({ isActive }) => "nav-link" + (isActive ? " active" : "")}>SKU名管理</NavLink> {/* SKU名管理へのリンクを追加 */}
           </li>
            <li className="nav-item">
              <NavLink to="/parent-sku-names" className={({ isActive }) => "nav-link" + (isActive ? " active" : "")}>親SKU登録</NavLink> {/* 親SKU登録へのリンクを追加 */}
            </li>
            <li className="nav-item">
              <NavLink to="/purchase" className={({ isActive }) => "nav-link" + (isActive ? " active" : "")}>仕入れ登録</NavLink>
            </li>
          </ul>
        </nav>
      </header>
      <main className="app-main">
        <Routes>
          <Route path="/" element={<UploadPage />} />
          <Route path="/monthly-summary" element={<MonthlySummaryPage />} />
          <Route path="/sku-names" element={<SkuNamePage />} /> {/* SKU名管理のルーティングを追加 */}
          <Route path="/parent-sku-names" element={<ParentSkuPage />} /> {/* 親SKU登録のルーティングを追加 */}
          <Route path="/purchase" element={<PurchasePage />} />
        </Routes>
      </main>
    </div>
  );
}

export default App;
